Rails.application.config.assets.precompile += %w( supersized.css )
Rails.application.config.assets.precompile += %w( supersized.shutter.js )
Rails.application.config.assets.precompile += %w( jquery.easing.min.js )
Rails.application.config.assets.precompile += %w( supersized.3.2.7.min.js )
Rails.application.config.assets.precompile += %w( supersized.shutter.min.js )